#!/usr/bin/env bash
# Script installs nginx and configures it to listen on port 80
# sets up a server block

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx Full'
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
