#!/usr/bin/env bash
# Script installs nginx and configures it to listen on port 80
# sets up a server block

sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start