#!/usr/bin/env bash
# Script installs nginx and configures it to listen on port 80
# sets up a server block

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo nginx -t
sudo service nginx start
