#!/usr/bin/env bash
# Configures Nginx server so that /redirect_me is redirecting to another page

sudo apt-get -y update
sudo apt-get -y install nginx
# Allow HTTP traffic through the firewall
sudo ufw allow 'Nginx Full'

# Create a simple "Hello World!" index page
echo "Hello World!" | sudo tee /var/www/html/index.html

#redirection
#sed -i "/^\tlocation \// i\ /server_name _;/a \
#\tlocation /redirect_me {\
#\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\
#\t}" /etc/nginx/sites-available/default
sudo tee -a /etc/nginx/sites-available/default <<EOL
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
EOL

# Restart Nginx to apply changes
sudo /etc/init.d/nginx restart
