#!/usr/bin/env bash
#redirections
str_red="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i "s/server_name _;/$str_red/" /etc/nginx/sites-enabled/default
sudo service nginx restart
