#!/usr/bin/env bash
# performs a permanent (301) redirection of /redirect_me

sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$replacement/" /etc/nginx/sites-available/default
sudo service nginx restart