#!/usr/bin/env bash
# Installs and configures HAProxy

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get install -y haproxy=2.0.\*

tmp=\
"
	frontend myfrontend
		bind *:80
		mode http
		default_backend mybackend
	backend mybackend
		balance roundrobin
		server 97182-web-01 52.72.66.208:80 check
		server 97182-web-02 35.175.64.229:80 check
"
echo "$tmp" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo haproxy -c -f /etc/haproxy/haproxy.cfg
sudo service haproxy restart
