#!/usr/bin/env bash
#the 9th iteration, displays Best School and then Hi
i=0
while [ $i -lt 10 ];
do
	if [ $i -eq 8 ];
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((i++))
done
