#!/usr/bin/env bash
#script that configures an Ubuntu server with the below requirements.
#Requirements:
#
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8.

cp /etc/hosts ~/host.new
echo "127.0.0.2		localhost" > ~/host.new
echo "8.8.8.8		facebook.com" >> ~/host.new
cp -f ~/host.new /etc/hosts
